name: "Check and Deploy"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  push:
    paths:
      - altstore-source.json
      - check.mjs
      - .github/workflows/check-and-deploy.yml
  pull_request:
    paths:
      - altstore-source.json
      - check.mjs
      - .github/workflows/check-and-deploy.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: node check.mjs

  deploy-source-file:
    needs: check-urls
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::570620554963:role/github_actions_freedomstore_source
          aws-region: eu-central-1

      - name: Upload source file to s3 bucket
        run: |
          aws s3 cp ./altstore-source.json s3://vexl-source-freedomstore/altstore-source.json
          aws cloudfront create-invalidation --distribution-id EV9ASNJTGD50D --paths "/"
