name: "[Deploy] altstore source file"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  push:
    branches:
      - main
    paths:
     - altstore-source.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-source-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::570620554963:role/github_actions_freedomstore_source
          aws-region: eu-central-1

      - name: Upload source file to s3 bucket
        run: |
          aws s3 cp ./altstore-source.json s3://vexl-source-freedomstore/altstore-source.json
          aws cloudfront create-invalidation --distribution-id EV9ASNJTGD50D --paths "/"
